// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphMacOSLobAppRequestBuilder builds and executes requests for operations under \deviceAppManagement\mobileApps\{mobileApp-id}\graph.macOSLobApp
type MobileAppsItemGraphMacOSLobAppRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewMobileAppsItemGraphMacOSLobAppRequestBuilderInternal instantiates a new MobileAppsItemGraphMacOSLobAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSLobAppRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSLobAppRequestBuilder {
	m := &MobileAppsItemGraphMacOSLobAppRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.macOSLobApp", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphMacOSLobAppRequestBuilder instantiates a new MobileAppsItemGraphMacOSLobAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSLobAppRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSLobAppRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphMacOSLobAppRequestBuilderInternal(urlParams, requestAdapter)
}

// ContentVersions provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
// returns a *MobileAppsItemGraphMacOSLobAppContentVersionsRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSLobAppRequestBuilder) ContentVersions() *MobileAppsItemGraphMacOSLobAppContentVersionsRequestBuilder {
	return NewMobileAppsItemGraphMacOSLobAppContentVersionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
