// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphWin32LobAppRequestBuilder builds and executes requests for operations under \deviceAppManagement\mobileApps\{mobileApp-id}\graph.win32LobApp
type MobileAppsItemGraphWin32LobAppRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewMobileAppsItemGraphWin32LobAppRequestBuilderInternal instantiates a new MobileAppsItemGraphWin32LobAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphWin32LobAppRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphWin32LobAppRequestBuilder {
	m := &MobileAppsItemGraphWin32LobAppRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.win32LobApp", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphWin32LobAppRequestBuilder instantiates a new MobileAppsItemGraphWin32LobAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphWin32LobAppRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphWin32LobAppRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphWin32LobAppRequestBuilderInternal(urlParams, requestAdapter)
}

// ContentVersions provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
// returns a *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder when successful
func (m *MobileAppsItemGraphWin32LobAppRequestBuilder) ContentVersions() *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder {
	return NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
