// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	"context"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
type MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderGetQueryParameters the list of content versions for this app. This property is read-only.
type MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderGetQueryParameters struct {
	// Include count of items
	Count *bool "uriparametername:\"%24count\""
	// Expand related entities
	Expand []string "uriparametername:\"%24expand\""
	// Filter items by property values
	Filter *string "uriparametername:\"%24filter\""
	// Order items by property values
	Orderby []string "uriparametername:\"%24orderby\""
	// Search items by search phrases
	Search *string "uriparametername:\"%24search\""
	// Select properties to be returned
	Select []string "uriparametername:\"%24select\""
	// Skip the first n items
	Skip *int32 "uriparametername:\"%24skip\""
	// Show only the first n items
	Top *int32 "uriparametername:\"%24top\""
}

// ByMobileAppContentId provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
// returns a *MobileAppsItemGraphWin32LobAppContentVersionsMobileAppContentItemRequestBuilder when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) ByMobileAppContentId(mobileAppContentId string) *MobileAppsItemGraphWin32LobAppContentVersionsMobileAppContentItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if mobileAppContentId != "" {
		urlTplParams["mobileAppContent%2Did"] = mobileAppContentId
	}
	return NewMobileAppsItemGraphWin32LobAppContentVersionsMobileAppContentItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderInternal instantiates a new MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder and sets the default values.
func NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder {
	m := &MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.win32LobApp/contentVersions{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder instantiates a new MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder and sets the default values.
func NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get the list of content versions for this app. This property is read-only.
// returns a []byte when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderGetQueryParameters]) ([]byte, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.([]byte), nil
}

// Post create new navigation property to contentVersions for deviceAppManagement
// returns a []byte when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) Post(ctx context.Context, body []byte, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) ([]byte, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.([]byte), nil
}

// ToGetRequestInformation the list of content versions for this app. This property is read-only.
// returns a *RequestInformation when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation create new navigation property to contentVersions for deviceAppManagement
// returns a *RequestInformation when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) ToPostRequestInformation(ctx context.Context, body []byte, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	requestInfo.SetStreamContentAndContentType(body, "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder when successful
func (m *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder) WithUrl(rawUrl string) *MobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder {
	return NewMobileAppsItemGraphWin32LobAppContentVersionsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
