// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	"context"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder provides operations to manage the files property of the microsoft.graph.mobileAppContent entity.
type MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderGetQueryParameters the list of files for this app content version.
type MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderGetQueryParameters struct {
	// Expand related entities
	Expand []string "uriparametername:\"%24expand\""
	// Select properties to be returned
	Select []string "uriparametername:\"%24select\""
}

// Commit provides operations to call the commit method.
// returns a *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemCommitRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder) Commit() *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemCommitRequestBuilder {
	return NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemCommitRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderInternal instantiates a new MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder {
	m := &MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.macOSDmgApp/contentVersions/{mobileAppContent%2Did}/files/{mobileAppContentFile%2Did}{?%24expand,%24select}", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder instantiates a new MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get the list of files for this app content version.
// returns a []byte when successful
func (m *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderGetQueryParameters]) ([]byte, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.([]byte), nil
}

// RenewUpload provides operations to call the renewUpload method.
// returns a *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemRenewUploadRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder) RenewUpload() *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemRenewUploadRequestBuilder {
	return NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesItemRenewUploadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// ToGetRequestInformation the list of files for this app content version.
// returns a *RequestInformation when successful
func (m *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder) WithUrl(rawUrl string) *MobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder {
	return NewMobileAppsItemGraphMacOSDmgAppContentVersionsItemFilesMobileAppContentFileItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
