// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphMacOSPkgAppRequestBuilder builds and executes requests for operations under \deviceAppManagement\mobileApps\{mobileApp-id}\graph.macOSPkgApp
type MobileAppsItemGraphMacOSPkgAppRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewMobileAppsItemGraphMacOSPkgAppRequestBuilderInternal instantiates a new MobileAppsItemGraphMacOSPkgAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSPkgAppRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSPkgAppRequestBuilder {
	m := &MobileAppsItemGraphMacOSPkgAppRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.macOSPkgApp", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphMacOSPkgAppRequestBuilder instantiates a new MobileAppsItemGraphMacOSPkgAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSPkgAppRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSPkgAppRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphMacOSPkgAppRequestBuilderInternal(urlParams, requestAdapter)
}

// ContentVersions provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
// returns a *MobileAppsItemGraphMacOSPkgAppContentVersionsRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSPkgAppRequestBuilder) ContentVersions() *MobileAppsItemGraphMacOSPkgAppContentVersionsRequestBuilder {
	return NewMobileAppsItemGraphMacOSPkgAppContentVersionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
