// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemGraphMacOSDmgAppRequestBuilder builds and executes requests for operations under \deviceAppManagement\mobileApps\{mobileApp-id}\graph.macOSDmgApp
type MobileAppsItemGraphMacOSDmgAppRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewMobileAppsItemGraphMacOSDmgAppRequestBuilderInternal instantiates a new MobileAppsItemGraphMacOSDmgAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSDmgAppRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSDmgAppRequestBuilder {
	m := &MobileAppsItemGraphMacOSDmgAppRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/graph.macOSDmgApp", pathParameters),
	}
	return m
}

// NewMobileAppsItemGraphMacOSDmgAppRequestBuilder instantiates a new MobileAppsItemGraphMacOSDmgAppRequestBuilder and sets the default values.
func NewMobileAppsItemGraphMacOSDmgAppRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemGraphMacOSDmgAppRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemGraphMacOSDmgAppRequestBuilderInternal(urlParams, requestAdapter)
}

// ContentVersions provides operations to manage the contentVersions property of the microsoft.graph.mobileLobApp entity.
// returns a *MobileAppsItemGraphMacOSDmgAppContentVersionsRequestBuilder when successful
func (m *MobileAppsItemGraphMacOSDmgAppRequestBuilder) ContentVersions() *MobileAppsItemGraphMacOSDmgAppContentVersionsRequestBuilder {
	return NewMobileAppsItemGraphMacOSDmgAppContentVersionsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
