// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package deviceappmanagement

import (
	"context"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileAppsItemAssignmentsRequestBuilder provides operations to manage the assignments property of the microsoft.graph.mobileApp entity.
type MobileAppsItemAssignmentsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// MobileAppsItemAssignmentsRequestBuilderGetQueryParameters the list of group assignments for this mobile app.
type MobileAppsItemAssignmentsRequestBuilderGetQueryParameters struct {
	// Include count of items
	Count *bool "uriparametername:\"%24count\""
	// Expand related entities
	Expand []string "uriparametername:\"%24expand\""
	// Filter items by property values
	Filter *string "uriparametername:\"%24filter\""
	// Order items by property values
	Orderby []string "uriparametername:\"%24orderby\""
	// Search items by search phrases
	Search *string "uriparametername:\"%24search\""
	// Select properties to be returned
	Select []string "uriparametername:\"%24select\""
	// Skip the first n items
	Skip *int32 "uriparametername:\"%24skip\""
	// Show only the first n items
	Top *int32 "uriparametername:\"%24top\""
}

// NewMobileAppsItemAssignmentsRequestBuilderInternal instantiates a new MobileAppsItemAssignmentsRequestBuilder and sets the default values.
func NewMobileAppsItemAssignmentsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemAssignmentsRequestBuilder {
	m := &MobileAppsItemAssignmentsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/deviceAppManagement/mobileApps/{mobileApp%2Did}/assignments{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top}", pathParameters),
	}
	return m
}

// NewMobileAppsItemAssignmentsRequestBuilder instantiates a new MobileAppsItemAssignmentsRequestBuilder and sets the default values.
func NewMobileAppsItemAssignmentsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileAppsItemAssignmentsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileAppsItemAssignmentsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get the list of group assignments for this mobile app.
// returns a []byte when successful
func (m *MobileAppsItemAssignmentsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemAssignmentsRequestBuilderGetQueryParameters]) ([]byte, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.([]byte), nil
}

// ToGetRequestInformation the list of group assignments for this mobile app.
// returns a *RequestInformation when successful
func (m *MobileAppsItemAssignmentsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileAppsItemAssignmentsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *MobileAppsItemAssignmentsRequestBuilder when successful
func (m *MobileAppsItemAssignmentsRequestBuilder) WithUrl(rawUrl string) *MobileAppsItemAssignmentsRequestBuilder {
	return NewMobileAppsItemAssignmentsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
