---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .mise/**
      - .github/workflows/docs.yaml
  pull_request:
    paths:
      - docs/**
      - .mise/**
      - .github/workflows/docs.yaml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_NO_HOOKS: "1"

jobs:
  build:
    name: Build docs site
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build docs site
        uses: home-operations/.github/actions/docs-build@497a09d6c938860e9330aeb7537f2b3362834ba9 # docs-build-v1.0.2
        with:
          path: ./docs/build
          deploy: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}

  publish:
    name: Publish to GitHub Pages
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    needs:
      - build
    runs-on: ubuntu-26.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
