---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  goreleaser:
    name: GoReleaser
    uses: $/.github/workflows/goreleaser.yaml
    permissions:
      contents: write
    with:
      snapshot: false
